### ISSUE TITLE
Bluetooth menu not showing up

### ISSUE THREAD

**Issue by Henne1191** [bjarosze/gnome-bluetooth-quick-connect#21]
I am on Ubuntu 20.04 using the GNOME desktop session and for me the bluetooth menu does not show up after installing the extension. Also tried reboot and reinstalling bluez & gnome-bluetooth.

![grafik](https://user-images.githubusercontent.com/37246482/82800847-a59ec300-9e7c-11ea-8008-0f0e40ff5018.png)

**Comment by bjarosze** [comment]
Does bluetooth menu show up without extension? Because this extension does not add bluetooth menu itself. Menu is there by default in gnome. 

Maybe your bluetooth device is not detected properly? What returns this command? 
`bluetoothctl -- list`

And can you show me a logs from extension? 
`journalctl -b /usr/bin/gnome-shell | grep "bluetooth-quick-connect"`

**Comment by Henne1191** [comment]
I don't quite understand this issue. There seems to be something wrong with Bluetooth in general when using multiple user accounts.

It seems like the menu only appears for the first user logging in when Bluetooth is disabled. The menu behaves really weird but I don't think it is related to this extension because I tried a few things and see the same behaviour when not using this extension.

**Comment by pitlochry** [comment]
[fixed](https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/1426) in gnome 3.38
